### ISSUE TITLE
The paper you referenced in MDVRP

### ISSUE THREAD

**Issue by jingjingchen018** [Lagostra/MDVRP#1]
Hi, I'm interested in MDVRP and your code is very helpful to me. Thanks a lot.  I'm wondering your reference about your code. I want  to acknowledge you and this article in my paper. Please tell me the paper you referenced. Thank you. 
Merry Christmas!

**Comment by eivindlie** [comment]
Hi, and sorry for the late response - I didn't notice this issue before now. This is a project done for a university course roughly a year ago, and I must admit that I cannot remember what I used for reference - it was likely lecture notes that are not openly available. I must also warn you that the results were indeed quite poor. You might be able to achieve better results with more time spent tweaking, but it is also quite possible that there are deeper-lying problems with the implementation... Sorry that I couldn't be of more help!

**Comment by jingjingchen018** [comment]
It's OK. Many thanks. I will do something based on it.

**Comment by rampallishyam** [comment]
Just the issue I was wondering about. @jingjingchen018 , did you find any implementation better?
